import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/home1" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Home1
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/shop" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Shop
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/productinside" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Productinside
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/about" style={{ color: "#87CEFA", textDecoration: "none" }}>
            About
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/contacts" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Contacts
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/login" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Login
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/signup" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Signup
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/myaccoount" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Myaccoount
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/cart" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Cart
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/checkout" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Checkout
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/page" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Page
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
